language: cpp
sudo: required
script: ./.travis/build.sh
git:
  submodules: false
  
sources: &sources
  - sourceline: "deb http://apt.llvm.org/precise/ llvm-toolchain-precise main"
  - key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
  - ubuntu-toolchain-r-test
  - george-edison55-precise-backports

packages: &packages
  - gcc-6
  - clang-3.8
  - cmake
  - cmake-data

base_configuration: &base_configuration
  - build_type="debug"
  - build_type="release"
  - build_type="debug" static_libraries="TRUE"
  - build_type="release" static_libraries="TRUE"

addons:
  apt:
    sources: *source
    packages: *packages
  
matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        global: VERSION=6
        matrix: *base_configuration
    - os: linux
      compiler: gcc
      env: VERSION=6 build_type=coverage
    - os: linux
      compiler: clang
      env:
        global: VERSION=3.8
        matrix: *base_configuration
    - os: linux
      compiler: clang
      env:
        global: VERSION=3.8
        matrix:        
          - appended_flags="-fsanitize=address -fno-omit-frame-pointer"
          - appended_flags="-fsanitize=memory -fno-omit-frame-pointer"
          - appended_flags="-fsanitize=undefined -fno-omit-frame-pointer"
          - appended_flags="-fsanitize=cfi -flto -fno-omit-frame-pointer"
 
#     - os: osx
#       osx_image: xcode8
#       compiler: clang
#       script: ./.travis/build.sh
#       env:
#         matrix:
#           - build_type="release"
#           - build_type="debug"
#           - static_libraries="TRUE"
#           - static_libraries="FALSE"
