language: cpp
matrix:
  include:
    - os: linux
      script: ./.travis/build.sh
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'        
            - george-edison55-precise-backports
          packages:
            - g++-6
            - clang++-3.8
            - cmake
            - cmake-data
      git:
        submodules: false
      env:
        matrix:
          - CXX=g++-6
          - CXX=clang-3.8
          - build_type="debug"
          - build_type="release"
          - static_libraries="TRUE"
          - static_libraries="FALSE"
        
    - os: linux
      script: ./.travis/build.sh
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'        
            - george-edison55-precise-backports
          packages:
            - clang-3.8
            - cmake
            - cmake-data
      submodules: false
      env:
        global:
          - CXX=clang++-3.8
          - build_type="debug"
        matrix:
          - appended_flags="-fsanitize=address -fno-omit-frame-pointer"
          - appended_flags="-fsanitize=memory -fno-omit-frame-pointer"
          - appended_flags="-fsanitize=undefined -fno-omit-frame-pointer"
          - appended_flags="-fsanitize=cfi -flto -fno-omit-frame-pointer"

    - os: linux
      script: ./.travis/build.sh
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - cmake
            - cmake-data
      submodules: false
      env:
        - CXX=g++-6
        - build_type="coverage"

    - os: osx
      osx_image: xcode8
      compiler: clang
      script: ./.travis/build.sh
      env:
        matrix:
          - build_type="release"
          - build_type="debug"
          - static_libraries="TRUE"
          - static_libraries="FALSE"
