environment:
  machine_user: test_user
  machine_pass: Pass@word1
  mingw_directory: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin
  CTEST_OUTPUT_ON_FAILURE: 1  

  matrix:
    - BUILD_TYPE: release
      STATIC_LIBRARIES: FALSE
      
    - BUILD_TYPE: release
      STATIC_LIBRARIES: TRUE
      
install:
  - ps: net user /add $env:machine_user $env:machine_pass
  - ps: net localgroup administrators $env:machine_user /add

before_build:
  - set Path=%mingw_directory%;%Path%
  - g++ --version
  - mingw32-make --version
  - cmake --version
  - ps: py -3 ./fetch_subprojects.py
  - ps: Get-Command sh.exe -All | Remove-Item
  - ps: new-item -Name build -ItemType directory
  - ps: cd build  
  - cmake .. -G "MinGW Makefiles" -Dbuild_type=%BUILD_TYPE% -Dstatic_libraries=%STATIC_LIBRARIES%

build_script:
  - cmake --build . --use-stderr --target all -- -j%NUMBER_OF_PROCESSORS%

after_build:
  - cmake --build . --use-stderr --target test
