cache:
- x86_64-5.3.0-release-win32-seh-rt_v4-rev0.7z

environment:
  machine_user: test_user
  machine_pass: Pass@word1
  mingw_directory: mingw64
  mingw_url: "https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/5.3.0/threads-win32/seh/x86_64-5.3.0-release-win32-seh-rt_v4-rev0.7z/download"
  mingw_archive: "x86_64-5.3.0-release-win32-seh-rt_v4-rev0.7z"
  CTEST_OUTPUT_ON_FAILURE: 1  

install:
  - ps: net user /add $env:machine_user $env:machine_pass
  - ps: net localgroup administrators $env:machine_user /add
  - if not exist "%mingw_archive%" appveyor DownloadFile "%mingw_url%" -FileName "%mingw_archive%"
  - 7z x -y "%mingw_archive%" > nul

before_build:
  - set Path=%CD%\%mingw_directory%\bin;%Path%
  - g++ --version
  - mingw32-make --version
  - cmake --version
  - ps: py -3 ./fetch_subprojects.py
  - ps: Get-Command sh.exe -All | Remove-Item
  - ps: new-item -Name build -ItemType directory
  - ps: cd build  
  - cmake .. -G "MinGW Makefiles"

build_script:
  - cmake --build . --use-stderr --target all -- -j%NUMBER_OF_PROCESSORS%

after_build:
  - cmake --build . --use-stderr --target test
